name: Audit

on:
  push:
    branches: [main]
  pull_request:

env:
  GO_VERSION: 1.18

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: latest
        # skip cache because of flaky behaviors
        skip-build-cache: true
        skip-pkg-cache: true
